export const USER_ERROR_CODES = {
  CANNOT_CHANGE_OWN_ROLE: 'CANNOT_CHANGE_OWN_ROLE', // 403 Forbidden

  CANNOT_CHANGE_OWN_STATUS: 'CANNOT_CHANGE_OWN_STATUS', // 403 Forbidden

  CANNOT_BLOCK_ADMIN: 'CANNOT_BLOCK_ADMIN', // 403 Forbidden

  USER_NOT_FOUND: 'USER_NOT_FOUND', // 404 Not Found

  ROLE_ALREADY_ASSIGNED: 'ROLE_ALREADY_ASSIGNED', // 409 Conflict

  STATUS_ALREADY_ASSIGNED: 'STATUS_ALREADY_ASSIGNED', // 409 Conflict
} as const;

export type UserErrorCode =
  (typeof USER_ERROR_CODES)[keyof typeof USER_ERROR_CODES];
