export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS', // 401 Unauthorized

  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED', // 403 Forbidden
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS', // 409 Conflict
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED', // 409 Conflict

  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED', // 403 Forbidden

  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN', // 400 Bad Request

  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN', // 401 Unauthorized
  EXPIRED_REFRESH_TOKEN: 'EXPIRED_REFRESH_TOKEN', // 401 Unauthorized

  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN', // 401 Unauthorized

  INVALID_EMAIL_VERIFICATION_TOKEN: 'INVALID_EMAIL_VERIFICATION_TOKEN', // 400 Bad Request
  EXPIRED_EMAIL_VERIFICATION_TOKEN: 'EXPIRED_EMAIL_VERIFICATION_TOKEN', // 400 Bad Request

  PASSWORD_ALREADY_USED: 'PASSWORD_ALREADY_USED', // 409 Conflict
} as const;

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
