export const AUTH_EVENT_CODES = {
  ACCOUNT_ACTIVATED: 'ACCOUNT_ACTIVATED',

  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

  LOGOUT_ALL_SUCCESS: 'LOGOUT_ALL_SUCCESS',

  EMAIL_VERIFICATION_EMAIL_SENT: 'EMAIL_VERIFICATION_EMAIL_SENT',

  PASSWORD_RESET_EMAIL_SENT: 'PASSWORD_RESET_EMAIL_SENT',

  PASSWORD_CHANGE_EMAIL_SENT: 'PASSWORD_CHANGE_EMAIL_SENT',

  PASSWORD_UPDATE_SUCCESS: 'PASSWORD_RESET_SUCCESS',
} as const;

export type AuthEventCode =
  (typeof AUTH_EVENT_CODES)[keyof typeof AUTH_EVENT_CODES];
